import { AlertCircle, Check, Loader2, Search, X } from 'lucide-react';
import type { ReactNode } from 'react';

export function LoadingState({ label = 'Loading your workspace' }: { label?: string }) {
  return <div className="surface flex min-h-[220px] items-center justify-center"><div className="flex items-center gap-3 text-sm text-[#67847b]"><Loader2 className="animate-spin" size={18} /> {label}</div></div>;
}
export function ErrorState({ message = 'We could not load this view.', onRetry }: { message?: string; onRetry?: () => void }) {
  return <div className="surface flex min-h-[220px] flex-col items-center justify-center gap-3 p-8 text-center"><div className="grid h-10 w-10 place-items-center rounded-full bg-[#fff0ed] text-[#c55347]"><AlertCircle size={19} /></div><p className="text-sm font-semibold text-[#5e423e]">{message}</p>{onRetry && <button onClick={onRetry} className="rounded-lg bg-[#e7f2ed] px-4 py-2 text-xs font-bold text-[#21614e]" data-testid="button-retry">Try again</button>}</div>;
}
export function EmptyState({ title, action }: { title: string; action?: ReactNode }) { return <div className="flex min-h-[190px] flex-col items-center justify-center gap-3 p-8 text-center"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-[#e7f2ed] text-[#2e725d]"><Check size={20} /></div><p className="text-sm font-semibold text-[#638078]">{title}</p>{action}</div>; }
export function SearchField({ value, onChange, placeholder = 'Search records...' }: { value: string; onChange: (value: string) => void; placeholder?: string }) { return <div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-[#78978e]" size={16} /><input value={value} onChange={e => onChange(e.target.value)} placeholder={placeholder} className="h-10 w-full rounded-xl border bg-white pl-9 pr-9 text-sm outline-none transition placeholder:text-[#9bb0aa] focus:border-[#3e9775] focus:ring-2 focus:ring-[#cde9dc]" data-testid="input-search" />{value && <button onClick={() => onChange('')} className="absolute right-3 top-1/2 -translate-y-1/2 text-[#78978e]" data-testid="button-clear-search"><X size={14} /></button>}</div>; }
export function Modal({ title, children, onClose }: { title: string; children: ReactNode; onClose: () => void }) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#123d32]/35 p-4 backdrop-blur-[2px]"><div className="max-h-[92vh] w-full max-w-xl overflow-y-auto rounded-2xl border bg-[#fbfefc] p-6 shadow-2xl animate-rise"><div className="mb-5 flex items-start justify-between"><h2 className="font-display text-xl font-extrabold text-[#193f35]">{title}</h2><button onClick={onClose} className="rounded-lg p-1 text-[#709087] hover:bg-[#eaf3ee]" aria-label="Close dialog" data-testid="button-close-modal"><X size={18} /></button></div>{children}</div></div>; }